name: xendit
description: unofficial library for interact with api xendit payment support cross platform.
version: 0.0.9
homepage: https://github.com/azkadev/xendit/
repository: https://github.com/azkadev/xendit/
issue_tracker: https://github.com/azkadev/xendit/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  web_scraper: ^0.1.4

dependencies: 
  galaxeus_lib: ^0.0.47
  http: ^0.13.5
