name: xendit
description: unofficial library for interact with api xendit payment support cross platform.
version: 0.0.14
homepage: https://github.com/azkadev/xendit/
repository: https://github.com/azkadev/xendit/
issue_tracker: https://github.com/azkadev/xendit/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.0

dependencies: 
  galaxeus_lib: ^0.0.64
  http: ^0.13.6
