name: 'xendit'
description: 'unofficial library for interact with api xendit payment support cross platform.'
version: '0.0.25'
homepage: 'https://github.com/azkadev/xendit/'
repository: 'https://github.com/azkadev/xendit/'
issue_tracker: 'https://github.com/azkadev/xendit/issues'
documentation: 'https://youtube.com/@azkadev'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dev_dependencies: 
  lints: '^4.0.0'
  test: 'any'
dependencies: 
  general_lib: '^0.0.46'
  http: '^1.1.2'
  path: '^1.9.0'
dependency_overrides: 
  pointycastle: '3.8.0'
funding: 
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
